server:
  port: 52297
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liucheng2997/SpringCloud-Config-Center.git
      label=master: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/

